# Copyright (c) 2019-2020 Advanced Micro Devices, Inc. All rights reserved.
# This Dockerfile provides a starting point for a ROCm installation of rccl

# Parameters related to building rccl
ARG base_image

FROM ${base_image}
LABEL maintainer="rccl-maintainer@amd.com"

USER root
ARG user_uid

# Set MOFED version, OS version and platform
ENV MOFED_VER 5.0-2.1.8.0
ENV OS_VER rhel8.1
ENV PLATFORM x86_64

# Install dependent packages
RUN yum install -y \
    --nogpgcheck \
    autoconf \
    automake \
    bison \
    ca-certificates \
    chrpath \
    cmake \
    ethtool \
    flex \
    gcc-gfortran \
    git \
    graphviz \
    kmod \
    libmnl \
    libnl3 \
    libtool \
    lsof \
    m4 \
    make \
    numactl-libs \
    numactl-devel \
    openssh-server \
    pciutils \
    rock-dkms \
    rocm-cmake \
    sudo \
    swig \
    tcl \
    tcsh \
    tk \
    udev \
    wget

RUN echo '#!/bin/bash' | tee /etc/profile.d/devtoolset8.sh && echo \
    'source scl_source enable devtoolset-8' >>/etc/profile.d/devtoolset8.sh

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G video --shell /bin/bash jenkins && \
    echo '%video ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    chmod 400 /etc/sudoers.d/sudo-nopasswd

# Remove packages that conflict with MOFED
RUN yum remove -y \
    openmpi-devel

# Download and install Mellanox OFED
RUN wget --quiet http://content.mellanox.com/ofed/MLNX_OFED-${MOFED_VER}/MLNX_OFED_LINUX-${MOFED_VER}-${OS_VER}-${PLATFORM}.tgz && \
    tar -xvf MLNX_OFED_LINUX-${MOFED_VER}-${OS_VER}-${PLATFORM}.tgz

RUN MLNX_OFED_LINUX-${MOFED_VER}-${OS_VER}-${PLATFORM}/mlnxofedinstall --user-space-only --without-fw-update -q && \
    cd .. && \
    rm -rf ${MOFED_DIR} && \
    rm -rf *.tgz

# Allow OpenSSH to talk to containers without asking for confirmation
RUN mkdir -p /etc/ssh && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config
